name: 'PlatformIO Publish'
description: 'Deploy library to the PlatformIO Registry'
inputs:
  token:  # id of input
    description: 'PlatformIO Personal Authentication Token'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
branding:
  icon: 'package'
  color: 'orange'
